// HHFC RELEASE CANDIDATE FINAL
import { MissionDefinition } from "./missionTypes";

export const MISSION_WEEK: Record<"fighter" | "bettor" | "bookmaker", MissionDefinition[]> = {
  fighter: [
    {
      id: "fighter_day_1",
      role: "fighter",
      weekDay: 1,
      code: "JOUR 01",
      title: "OUVRE LA FIGHT ROOM",
      description: "Lis la card et entre dans la salle des combats.",
      cta: "OUVRIR FIGHT",
      targetScreen: "Fight",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 120, label: "XP" }, { kind: "prestige", value: 1, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "fighter_day_2",
      role: "fighter",
      weekDay: 2,
      code: "JOUR 02",
      title: "POSE TA DISPONIBILITÉ",
      description: "Réserve une vraie fenêtre dans le planner de la semaine.",
      cta: "OUVRIR PLANNER",
      targetScreen: "FightPlanner",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 160, label: "XP" }, { kind: "unlock", value: "ACCÈS COMBAT", label: "ACCÈS COMBAT" }],
      visibleOnHome: true,
    },
    {
      id: "fighter_day_3",
      role: "fighter",
      weekDay: 3,
      code: "JOUR 03",
      title: "REPÈRE L'ARÈNE",
      description: "Passe dans l'arène et prends la température de la soirée.",
      cta: "OUVRIR ARÈNE",
      targetScreen: "Arena",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 100, label: "XP" }, { kind: "prestige", value: 1, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "fighter_day_4",
      role: "fighter",
      weekDay: 4,
      code: "JOUR 04",
      title: "GARDE TON WALLET PRÊT",
      description: "Vérifie ton cash disponible avant de monter dans la carte.",
      cta: "OUVRIR WALLET",
      targetScreen: "Wallet",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 80, label: "XP" }, { kind: "priority", value: 1, label: "PRIORITÉ FIGHT" }],
      visibleOnHome: true,
    },
    {
      id: "fighter_day_5",
      role: "fighter",
      weekDay: 5,
      code: "JOUR 05",
      title: "TERMINE UN FIGHT",
      description: "Passe par le ring et termine ton premier combat réel.",
      cta: "VOIR FIGHT",
      targetScreen: "Fight",
      progressTarget: 1,
      rewards: [{ kind: "cash", value: 25000, label: "CASH" }, { kind: "prestige", value: 2, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "fighter_day_6",
      role: "fighter",
      weekDay: 6,
      code: "JOUR 06",
      title: "PRENDS UNE VICTOIRE",
      description: "Fais tomber un adversaire pour faire grimper ton nom.",
      cta: "VOIR RÉSULTAT",
      targetScreen: "Fight",
      progressTarget: 1,
      rewards: [{ kind: "cash", value: 50000, label: "CASH" }, { kind: "prestige", value: 3, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "fighter_day_7",
      role: "fighter",
      weekDay: 7,
      code: "JOUR 07",
      title: "TOUCHE LE TOP 20",
      description: "Monte dans la hiérarchie et fais entrer ton nom dans le classement.",
      cta: "VOIR TOP 20",
      targetScreen: "Leaderboard",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 250, label: "XP" }, { kind: "prestige", value: 5, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
  ],
  bettor: [
    {
      id: "bettor_day_1",
      role: "bettor",
      weekDay: 1,
      code: "JOUR 01",
      title: "OUVRE LA BET ROOM",
      description: "Viens lire la card et les cotes du jour.",
      cta: "OUVRIR BET",
      targetScreen: "Bet",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 120, label: "XP" }, { kind: "prestige", value: 1, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bettor_day_2",
      role: "bettor",
      weekDay: 2,
      code: "JOUR 02",
      title: "POSE TON PREMIER TICKET",
      description: "Verrouille un vrai pari sur la card ouverte.",
      cta: "PARIER",
      targetScreen: "Bet",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 150, label: "XP" }, { kind: "unlock", value: "SUIVI DE TICKET", label: "SUIVI DE TICKET" }],
      visibleOnHome: true,
    },
    {
      id: "bettor_day_3",
      role: "bettor",
      weekDay: 3,
      code: "JOUR 03",
      title: "REVIENS SUR LA CARD",
      description: "Relis les combats et les variations avant de rejouer.",
      cta: "LIRE LA CARD",
      targetScreen: "Bet",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 100, label: "XP" }, { kind: "prestige", value: 1, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bettor_day_4",
      role: "bettor",
      weekDay: 4,
      code: "JOUR 04",
      title: "FAIS DEUX TICKETS PROPRES",
      description: "Enchaîne sans te disperser et garde un jeu propre.",
      cta: "VOIR MES PARIS",
      targetScreen: "Bet",
      progressTarget: 2,
      rewards: [{ kind: "xp", value: 180, label: "XP" }, { kind: "prestige", value: 2, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bettor_day_5",
      role: "bettor",
      weekDay: 5,
      code: "JOUR 05",
      title: "VA CHERCHER UN TICKET GAGNANT",
      description: "Fais rentrer un gain réel dans ta bankroll.",
      cta: "SUIVRE MON TICKET",
      targetScreen: "Bet",
      progressTarget: 1,
      rewards: [{ kind: "cash", value: 20000, label: "CASH" }, { kind: "prestige", value: 2, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bettor_day_6",
      role: "bettor",
      weekDay: 6,
      code: "JOUR 06",
      title: "RENTRE DANS LE RYTHME",
      description: "Pose ton troisième ticket de la semaine.",
      cta: "REPARIER",
      targetScreen: "Bet",
      progressTarget: 3,
      rewards: [{ kind: "xp", value: 220, label: "XP" }, { kind: "prestige", value: 3, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bettor_day_7",
      role: "bettor",
      weekDay: 7,
      code: "JOUR 07",
      title: "CLOTURE TA SEMAINE",
      description: "Fais vivre ta bankroll et termine ta semaine de jeu proprement.",
      cta: "VOIR BET",
      targetScreen: "Bet",
      progressTarget: 3,
      rewards: [{ kind: "xp", value: 250, label: "XP" }, { kind: "prestige", value: 4, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
  ],
  bookmaker: [
    {
      id: "bookmaker_day_1",
      role: "bookmaker",
      weekDay: 1,
      code: "JOUR 01",
      title: "OUVRE TON PANEL",
      description: "Entre dans ta salle de contrôle et active ton réseau.",
      cta: "OUVRIR BOOKMAKER",
      targetScreen: "BookmakerHome",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 120, label: "XP" }, { kind: "prestige", value: 1, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bookmaker_day_2",
      role: "bookmaker",
      weekDay: 2,
      code: "JOUR 02",
      title: "ACTIVE TON DOSSIER",
      description: "Fais la demande qui débloque ton accès réseau.",
      cta: "OUVRIR PANEL",
      targetScreen: "BookmakerHome",
      progressTarget: 1,
      rewards: [{ kind: "prestige", value: 2, label: "PRESTIGE" }, { kind: "unlock", value: "ACCÈS RÉSEAU", label: "ACCÈS RÉSEAU" }],
      visibleOnHome: true,
    },
    {
      id: "bookmaker_day_3",
      role: "bookmaker",
      weekDay: 3,
      code: "JOUR 03",
      title: "RETOURNE AU PANEL",
      description: "Reviens sur ton contrôle réseau et surveille le volume.",
      cta: "VOIR BOOKMAKER",
      targetScreen: "BookmakerHome",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 100, label: "XP" }, { kind: "prestige", value: 1, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bookmaker_day_4",
      role: "bookmaker",
      weekDay: 4,
      code: "JOUR 04",
      title: "METS TON CODE EN JEU",
      description: "Installe ta présence et prépare ton flux affilié.",
      cta: "VOIR MON CODE",
      targetScreen: "BookmakerHome",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 150, label: "XP" }, { kind: "priority", value: 1, label: "PRIORITÉ RÉSEAU" }],
      visibleOnHome: true,
    },
    {
      id: "bookmaker_day_5",
      role: "bookmaker",
      weekDay: 5,
      code: "JOUR 05",
      title: "FAIS RENTRER DU VOLUME",
      description: "Déclenche une vraie activité affiliée dans le réseau.",
      cta: "SUIVRE LE VOLUME",
      targetScreen: "BookmakerHome",
      progressTarget: 1,
      rewards: [{ kind: "commission", value: 15000, label: "COMMISSION" }, { kind: "prestige", value: 2, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bookmaker_day_6",
      role: "bookmaker",
      weekDay: 6,
      code: "JOUR 06",
      title: "ACTIVE UN PREMIER MEMBRE",
      description: "Fais exister au moins un affilié réellement actif dans ton réseau.",
      cta: "OUVRIR PANEL",
      targetScreen: "BookmakerHome",
      progressTarget: 1,
      rewards: [{ kind: "xp", value: 200, label: "XP" }, { kind: "prestige", value: 2, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
    {
      id: "bookmaker_day_7",
      role: "bookmaker",
      weekDay: 7,
      code: "JOUR 07",
      title: "MONTE TON NIVEAU RÉSEAU",
      description: "Fais monter ton réseau à trois affiliés actifs pour finir la semaine fort.",
      cta: "VOIR LE BILAN",
      targetScreen: "BookmakerHome",
      progressTarget: 3,
      rewards: [{ kind: "commission", value: 25000, label: "COMMISSION" }, { kind: "prestige", value: 4, label: "PRESTIGE" }],
      visibleOnHome: true,
    },
  ],
};

// HHFC FINAL RULES
// - launch mission catalog enabled
